services:
  next-app:
    container_name: denkweisen-mp2
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 8080:3000